### ISSUE TITLE
Unable to handle svg if PIL available

### ISSUE THREAD

**Issue by mayrholu** [sphinx-pyreverse/sphinx-pyreverse#40]
Hi, it seems that svg is only possible if PIL is not available. Otherwise PIL throws an Exception:

> PIL.UnidentifiedImageError: cannot identify image file ...

Maybe a try..except block could be added to [this section](https://github.com/alendit/sphinx-pyreverse/blob/f8ef3ad9c8b6710ac97cc3880887ddff73ccbfad/sphinx_pyreverse/uml_generate_directive.py#L172). Something like:
```
        if IMAGE:
            try:
                i = IMAGE.open(output_file)
            except UnidentifiedImageError:  # requires import
               pass
            else:
                image_width = i.size[0]
                if image_width * scale > max_width:
                    scale = max_width / image_width
```

**Comment by doublethefish** [comment]
PRs welcome 🤗
